# fly.toml app configuration file generated for cartesi-paio-still-sun-6544 on 2024-09-20T21:18:06Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'cartesi-paio-still-sun-6544'
primary_region = 'cdg'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'suspend'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
