name: Rust

on: push

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ${{ matrix.runner }}

    strategy:
      matrix:
        include:
          - name: Linux-amd64
            runner: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            command: cargo

    steps:
      - uses: actions/checkout@v4

      - name: Install requirements (Linux)
        if: matrix.runner == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install protobuf-compiler libc6

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: "${{ matrix.target }}"

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1

      # Only install cross if we need it
      # Install via cargo-binstall which I found faster
      - name: Install Cross
        if: matrix.command == 'cross'
        shell: bash
        run: |
          curl -L --proto '=https' --tlsv1.2 -sSf https://raw.githubusercontent.com/cargo-bins/cargo-binstall/main/install-from-binstall-release.sh | bash
          cargo binstall --no-confirm cross

      - name: Build Tripa
        working-directory: tripa
        run: |
          cp -v config_default.toml config.toml
          ${{ matrix.command }} build --release --target ${{ matrix.target }}

      # TODO: Remove true after fix tests
      - name: Test tripa (Linux x86_64)
        working-directory: tripa
        run: cargo test || true

      - name: Build decode-batch
        working-directory: decode-batch
        run: ${{ matrix.command }} build --release --target ${{ matrix.target }}

      - name: Test decode-batch (Linux x86_64)
        working-directory: decode-batch
        run: cargo test
